version: "3.8"

services:
  app:
    image: hexpm/elixir:1.18.2-erlang-27.2.1-debian-bookworm-20250113-slim
    environment:
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: elixir button.exs
